const cartActionTypes = {
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  CLEAR_CART_PRODUCTS: 'CLEAR_CART_PRODUCTS',
  TOGGLE_CART_VISIBLE: 'TOGGLE_CART_VISIBLE',
  CLEAR_PRODUCT_FROM_CART: 'CLEAR_PRODUCT_FROM_CART',
  DECREASE_PRODUCT_QUANTITY: 'DECREASE_PRODUCT_QUANTITY',
  INCREASE_PRODUCT_QUANTITY: 'INCREASE_PRODUCT_QUANTITY',
  FETCH_SHIPPING_RATES_START: 'FETCH_SHIPPING_RATES_START',
  FETCH_SHIPPING_RATES_SUCCESS: 'FETCH_SHIPPING_RATES_SUCCESS',
  FETCH_SHIPPING_RATES_FAILURE: 'FETCH_SHIPPING_RATES_FAILURE'
}

export default cartActionTypes;