const productActionTypes = {
  SET_PRODUCT_TYPES: 'SET_PRODUCT_TYPES',
  FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  FETCH_TYPES_START: 'FETCH_TYPES_START',
  FETCH_TYPES_SUCCESS: 'FETCH_TYPES_SUCCESS',
  FETCH_TYPES_FAILURE: 'FETCH_TYPES_FAILURE',
  CHANGE_CURRENCY: 'CHANGE_CURRENCY'
}

export default productActionTypes;